### ISSUE TITLE
disable_mobile setting

### ISSUE THREAD

**Issue by golles** [kartik-v/yii2-social#17]
I had:

```
'disable_mobile' => false
```

Which broke the whole widget, I fixed it by changing it into a string:

```
'disable_mobile' => 'false'
```

Should be easy to fix

**Comment by golles** [comment]
switching noscript to false does not work, as you set it in Widget init() line 113

**Comment by kartik-v** [comment]
Yes the params for the plugins must be passed with the right data type (_string_ in this case) as desired by the social plugin (e.g. `disable_mobile` property)

Not sure about `noscript` - can you share this and create another issue to reproduce this.
