### ISSUE TITLE
Implement vk plugin

### ISSUE THREAD

**Issue by vladim1** [kartik-v/yii2-social#21]
Is it possible to implement vk plugin? VK is a huge social network. VK is implemented as client in yii2-authclient extension ([link](http://www.yiiframework.com/doc-2.0/yii-authclient-clients-vkontakte.html)). It has well written [documentation](http://vk.com/dev/sites)

**Comment by kartik-v** [comment]
Currently strapped with time - will need to check back on this when I have time. Feel free to submit a PR if you want this faster.

**Comment by kartik-v** [comment]
This is now been incorporated. Check [the docs and demos](http://demos.krajee.com/social-details/vk).

**Comment by vladim1** [comment]
This is great! Thank you very much for your work!!!
