### ISSUE TITLE
PHP Recoverable Error – yii\base\ErrorException

### ISSUE THREAD

**Issue by joyit00** [kartik-v/yii2-social#27]
Argument 1 passed to Facebook\FacebookRequest::__construct() must be an instance of Facebook\FacebookSession, null given, called in F:\data\xampp\htdocs\wash\vendor\kartik-v\yii2-social\Module.php on line 224 and defined

**Comment by abdulquddus** [comment]
I am facing same issue Kartik please can you help on this.

**Comment by kartik-v** [comment]
You have not mentioned where and how you received the error.

The error mentions that you failed to pass a facebook session identifier.

If you are using facebook api, check the [documentation](http://demos.krajee.com/social#facebook-api) on how to use the facebook api

**Comment by abdulquddus** [comment]
Sorry I know question is closed but when I use this code.
$social = Yii::$app->getModule('social');
// Render the Login button
$url = Yii::$app->request->getAbsoluteUrl(); // or any absolute url you want to redirect
helper = $social->getFbLoginHelper($url);
$loginUrl = $helper->getLoginUrl();
echo Html::a('Facebook Login', $loginUrl, ['class'=>'btn btn-primary']);
 
// in your other action that processes the login
// use the output from the helper
$helper = $social->getFbLoginHelper($url); // the same url
$session = $social->getFbSession(['source'=>$helper]); // do anything with this session now
 
// for example get the graph user object for current user
$user = $social->getFbGraphUser($session);
echo 'User is ' . $user->getName(); 

the error goes when I comment out the last two lines

//$user = $social->getFbGraphUser($session);
//echo 'User is ' . $user->getName(); 

and button appears. If these lines are removed than how a session is created. thanks in advance.

**Comment by kartik-v** [comment]
An example set of codes are provided. But you need to use them carefully. NOTE:  not all code in the example is to be written altogether in the same view.

You need to read through the comments.

The button is created via `Html::a`

Subequently you need to write the rest of the code in the `loginUrl` controller action as mentioned in the comment

```php
// in your other action that processes the login
// use the output from the helper
```

**Comment by abdulquddus** [comment]
Thanks Karthik that was very helping.

**Comment by cpu555** [comment]
Please Karthik  I need your help i'm facing this error:
Argument 1 passed to Facebook\Helpers\FacebookRedirectLoginHelper::__construct() must be an instance of Facebook\Authentication\OAuth2Client, string given, called in /home/itenginn/public_html/let/vendor/kartik-v/yii2-social/Module.php on line 207 and defined

This my view:
<?php
/* @var $this yii\web\View */
use kartik\social\Module;
$this->title = 'Facebook';

?>
<h1>tools/facebook</h1>

<div class = row>

	<div class="col-lg-6" style="background-color: #fff;box-shadow: 10px 10px 5px #888888;border-style: solid;">
	</br>	
		Please login to facebook to start using this tool:
		<?php 
			$social = Yii::$app->getModule('social');
			$url = Yii::$app->request->getAbsoluteUrl(); // or any absolute url you want to redirect
			$helper = $social->getFbLoginHelper($url);
			$loginUrl = $helper->getLoginUrl();
			echo Html::a('Facebook Login', $loginUrl, ['class'=>'btn btn-primary']);
		?>
			
	</br>		
	</div>
	
</div>
