### ISSUE TITLE
Custom layout of share buttoms

### ISSUE THREAD

**Issue by lkyam** [kartik-v/yii2-social#44]
I have a question is posible customize the default button? For example I want to change the facebook share button by other layout.
Sorry for my English.
Best regards.

**Comment by kartik-v** [comment]
The customization options are limited to the options provided by the social plugin. So for facebook share button - [the configuration options for facebook share button](https://developers.facebook.com/docs/plugins/share-button) only can be used to customize. You cannot change the markup to whatever you want.
