### ISSUE TITLE
Undefined variable: js

### ISSUE THREAD

**Issue by hrupin** [kartik-v/yii2-social#48]
When trying to call
`<?= VKPlugin::widget(['apiId' => '********','type'=>VKPlugin::LIKE]); ?>`

Get the error

Undefined variable: js
`
191192193194195196197198199200201202203204205206207208209            $call     = "\$('#$id').html(VK.Share.button($params))";
        } else {
            $script   = 'openapi.js?116';
            $scriptId = 'vk_openapi_script_tag';
            $check    = 'VK.Widgets';
            $widget   = ucfirst(substr($this->type, 3));
            $call     = "VK.Widgets.$widget($params)";
            if ($this->_initVk) {
                $initOpts = Json::encode(['apiId' => $this->apiId, 'onlyWidgets' => true]);
                $js = "VK.init({$initOpts});\n$js"; <-------- Errore
            }
        }
 
        $view->registerJsFile('//vk.com/js/api/' . $script, ['async'=>true, 'id'=>$scriptId, 'position'=>View::POS_HEAD]);
        $js = <<< SCRIPT
if (window.VK && $check) {
    $call;
} else {
    \$('#$scriptId').load(function() {
`

$js = "VK.init({$initOpts});\n$js";

Please, tell me, what I do not correctly

**Comment by kartik-v** [comment]
Resolved via #51.
