### ISSUE TITLE
Twitter size issue

### ISSUE THREAD

**Issue by vladim1** [kartik-v/yii2-social#52]
Twitter share button button doesn't work with default size, it works only when 'large' size is specified

**Comment by vladim1** [comment]
When the size is set to ```default``` it still doesn't word. Example
```php
echo TwitterPlugin::widget([            
            'type' =>TwitterPlugin::SHARE,
            'settings' => ['size'=>'default']
        ]);
```

**Comment by kartik-v** [comment]
No this is not correct. You can check the [twitter share button demo](http://demos.krajee.com/twitter-plugin/share) for example, where both default and large size buttons are rendered.
