### ISSUE TITLE
Sessions are not active when updated facebook SDK to 5.1.4

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-social#55]
```php
$social = Yii::$app->getModule('social');
$fb = $social->getFb();
```
![download](https://cloud.githubusercontent.com/assets/8703419/15351607/48f11a24-1d0a-11e6-997d-791db93b2cc5.png)

**Comment by kartik-v** [comment]
Not sure on reproducing this. 

Check if it is related to #56
