### ISSUE TITLE
This extension should update the PHP Facebook SDK to v4

### ISSUE THREAD

**Issue by invaderhd** [kartik-v/yii2-social#6]
I notice that this extension use the PHP SKD v3, I think you should change to v4 to be more future proof.

Yii2 is brand new and a extension like yii2-social will be a most for many users, it deserves the last versions of social SDKs.

**Comment by kartik-v** [comment]
At this stage I am removing support for Facebook PHP SDK v3.0 in this repo.

Facebook PHP SDK 4.0 can be directly and separately installed via composer. So I am not including this in here as of now and would update later.

**Comment by kartik-v** [comment]
On second thoughts, I am adding PHP SDK 4.0 support inbuilt into the extension to do it easier.

**Comment by kartik-v** [comment]
Resolved with upgrade to release v1.3.0. Refer #13 for newer Facebook features.
