### ISSUE TITLE
Package facebook/php-sdk-v4 is abandoned

### ISSUE THREAD

**Issue by mauriziocingolani** [kartik-v/yii2-social#62]
I guess it's still working, but switching to facebook/graph-sdk will have us get rid of the nasty message when updating Composer.

**Comment by newscloud** [comment]
Getting this too Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.

**Comment by robov** [comment]
me too... and I do not know how to get rid of this msg
