### ISSUE TITLE
can i change the facebook icon for like and sharing

### ISSUE THREAD

**Issue by mohdbashir** [kartik-v/yii2-social#72]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-social.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/social) and [demos](http://demos.krajee.com/social-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-social version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/social-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-social without other plugins.

**Comment by ak868308** [comment]
I also need same thing

**Comment by kartik-v** [comment]
Extension uses default facebook, google, and other social plugin APIs for rendering widgets as embedded content. At this stage not possible in this extension... you may want to explore this using your own styling to overlap a contentand JS if needed.
